"""empty message

Revision ID: aa21727b28bc
Revises: ea6b92677d16
Create Date: 2024-01-04 18:50:49.721353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa21727b28bc'
down_revision = 'ea6b92677d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Item',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('imagePath', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Order',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('table', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Restaurants',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SubOrder',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('order', sa.String(length=150), nullable=False),
    sa.Column('table', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Table',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('position', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('position')
        batch_op.drop_column('restaurant')

    op.drop_table('Table')
    op.drop_table('SubOrder')
    op.drop_table('Restaurants')
    op.drop_table('Order')
    op.drop_table('Item')
    op.drop_table('Category')
    # ### end Alembic commands ###
