"""empty message

Revision ID: d0e04eb4521f
Revises: aa21727b28bc
Create Date: 2024-01-04 19:13:48.222877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e04eb4521f'
down_revision = 'aa21727b28bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Item_SubOrder',
    sa.Column('SubOrder', sa.Integer(), nullable=True),
    sa.Column('Item', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Item'], ['Item.id'], ),
    sa.ForeignKeyConstraint(['SubOrder'], ['SubOrder.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Item_SubOrder')
    # ### end Alembic commands ###
